# Geographical location to get temperature from
# This one is Helsinki University
latitude: "60.230477"
longitude: "25.018615"

# These elements must exist in the corresponding OpenSILEX instance
variable: "opensilex-test:id/variable/air_temperature_datalogging_degreecelsius/1"
provenance_uri: "opensilex-test:id/provenance/datalogging"
device_uri: "http://opensilex.test/id/device/datalogging_temperature"
device_rdf_type: "vocabulary:SensingDevice"
