# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ajout_uri_uc.py
# Created on: 2022-08-19 08:24:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: ajout_uri_uc <Couche_des_UC> <Sélectionner_le_champ_contenant_les_noms_des_UC> <Sélectionner_le_champ_qui_contiendra_les_URI_des_UC> <Couche_des_micro_parcelles> <Emplacement_de_la_nouvelle_couche_des_micro_parcelles_avec_l_URI_des_UC> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Modéliser les fonctions")

# Script arguments
Couche_des_UC = arcpy.GetParameterAsText(0)

Sélectionner_le_champ_contenant_les_noms_des_UC = arcpy.GetParameterAsText(1)

Sélectionner_le_champ_qui_contiendra_les_URI_des_UC = arcpy.GetParameterAsText(2)

Couche_des_micro_parcelles = arcpy.GetParameterAsText(3)

Emplacement_de_la_nouvelle_couche_des_micro_parcelles_avec_l_URI_des_UC = arcpy.GetParameterAsText(4)

# Local variables:
avec_uri_uc = Couche_des_UC
nom_UC = Couche_des_UC
uri_UC = Couche_des_UC

# Process: Calculer un champ
arcpy.CalculateField_management(Couche_des_UC, Sélectionner_le_champ_qui_contiendra_les_URI_des_UC, "\"phenotoul:id/scientific-object/so-\"+!%Sélectionner le champ contenant les noms des UC%!.lower()", "PYTHON", "")

# Process: Jointure spatiale
arcpy.SpatialJoin_analysis(Couche_des_micro_parcelles, Couche_des_UC, Emplacement_de_la_nouvelle_couche_des_micro_parcelles_avec_l_URI_des_UC, "JOIN_ONE_TO_ONE", "KEEP_COMMON", "", "WITHIN", "", "")

# Process: Obtenir une valeur de champ
arcpy.GetFieldValue_mb(Couche_des_UC, Sélectionner_le_champ_contenant_les_noms_des_UC, "Chaîne", "0")

# Process: Obtenir une valeur de champ (2)
arcpy.GetFieldValue_mb(Couche_des_UC, Sélectionner_le_champ_qui_contiendra_les_URI_des_UC, "Chaîne", "0")

