# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Creation_UC.py
# Created on: 2022-08-19 08:24:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Creation_UC <Entités_en_entrée__polygones_non_découpés_> <Cocher_les_champs_correspondant_à_des_facteurs__pour_fusionner_> <Créer_des_entités_multi_parties> <Indiquer_l_emplacement_du_fichier_en_sortie__couche_contenant_le_s__UC_avec_champs__uc__et__uri_uc__> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Entités_en_entrée__polygones_non_découpés_ = arcpy.GetParameterAsText(0)

Cocher_les_champs_correspondant_à_des_facteurs__pour_fusionner_ = arcpy.GetParameterAsText(1)

Créer_des_entités_multi_parties = arcpy.GetParameterAsText(2)
if Créer_des_entités_multi_parties == '#' or not Créer_des_entités_multi_parties:
    Créer_des_entités_multi_parties = "false" # provide a default value if unspecified

Indiquer_l_emplacement_du_fichier_en_sortie__couche_contenant_le_s__UC_avec_champs__uc__et__uri_uc__ = arcpy.GetParameterAsText(3)

# Local variables:
sortie = Indiquer_l_emplacement_du_fichier_en_sortie__couche_contenant_le_s__UC_avec_champs__uc__et__uri_uc__
sortie__2_ = sortie

# Process: Fusionner
arcpy.Dissolve_management(Entités_en_entrée__polygones_non_découpés_, Indiquer_l_emplacement_du_fichier_en_sortie__couche_contenant_le_s__UC_avec_champs__uc__et__uri_uc__, Cocher_les_champs_correspondant_à_des_facteurs__pour_fusionner_, "", Créer_des_entités_multi_parties, "DISSOLVE_LINES")

# Process: Ajouter un champ
arcpy.AddField_management(Indiquer_l_emplacement_du_fichier_en_sortie__couche_contenant_le_s__UC_avec_champs__uc__et__uri_uc__, "uc", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Ajouter un champ (2)
arcpy.AddField_management(sortie, "uri_uc", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

