# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Decoupage_allees.py
# Created on: 2022-08-19 08:25:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Decoupage_allees <Couche_de_lignes> <Distance_à_découper_de_part_et_d_autre_des_lignes> <Couche_de_polygones_à_découper> <Couche_de_polygones_découpés> 
# Description: 
# Il faut au préalable que la couche de lignes qui serviront à découper les polygones soit faite. On peut cependant utiliser directement la couche de passage tracteur ou la couche contenant les lignes de guidage/déclenchement (fmx). Si la largeur des allées n’est pas identique pour toute la plateforme, il faut créer un champ dans lequel on attribue à chaque ligne la distance à découper de part et d’autre de cette dernière.
# ___________________________________________________
# Notice de paramétrage :
# Couche de lignes : couche de lignes qui serviront pour le découpage.
# Distance : saisir la distance à découper de part et d’autre des lignes (avec ‘Unité linéaire’ cochée) avec séparateur décimal "," ou si la distance pour chaque ligne est indiquée dans la table attributaire de la couche de ligne : Cocher ‘Champ’ puis sélectionner le champ.
# ___________________________________________________
# Après exécution du modèle on obtient une nouvelle couche de polygones découpés (avec la même table attributaire que celle de la couche de polygone en entrée).

# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
Couche_de_lignes = arcpy.GetParameterAsText(0)

Distance_à_découper_de_part_et_d_autre_des_lignes = arcpy.GetParameterAsText(1)

Couche_de_polygones_à_découper = arcpy.GetParameterAsText(2)

Couche_de_polygones_découpés = arcpy.GetParameterAsText(3)

# Local variables:
Classe_d’entités_en_sortie = ""

# Process: Zone tampon
arcpy.Buffer_analysis(Couche_de_lignes, Classe_d’entités_en_sortie, Distance_à_découper_de_part_et_d_autre_des_lignes, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Effacer
arcpy.Erase_analysis(Couche_de_polygones_à_découper, Classe_d’entités_en_sortie, Couche_de_polygones_découpés, "")

