# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# gen_gabarit_phis_mp.py
# Created on: 2022-08-19 08:25:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: gen_gabarit_phis_mp <Couche_en_entrée> <Sélectionner_le_champ_comportant_l_alias> <Sélectionner_le_champ_comportant_le_n°_de_l_essai> <Sélectionner_le_champ_comportant_le_n°_du_bloc> <Sélectionner_le_champ_comportant_l_uri_de_l_uc> <Sélectionner_le_champ_comportant_l_uri_de_la_variété> <Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°1> <Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°2> <Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°3> <Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°4> <Donner_l_emplacement_et_le_nom_du_des_gabarits_csv_en_sortie> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Modéliser les fonctions")
arcpy.ImportToolbox("Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx")

# Script arguments
Couche_en_entrée = arcpy.GetParameterAsText(0)

Sélectionner_le_champ_comportant_l_alias = arcpy.GetParameterAsText(1)

Sélectionner_le_champ_comportant_le_n°_de_l_essai = arcpy.GetParameterAsText(2)

Sélectionner_le_champ_comportant_le_n°_du_bloc = arcpy.GetParameterAsText(3)

Sélectionner_le_champ_comportant_l_uri_de_l_uc = arcpy.GetParameterAsText(4)

Sélectionner_le_champ_comportant_l_uri_de_la_variété = arcpy.GetParameterAsText(5)

Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°1 = arcpy.GetParameterAsText(6)

Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°2 = arcpy.GetParameterAsText(7)

Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°3 = arcpy.GetParameterAsText(8)

Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°4 = arcpy.GetParameterAsText(9)

Donner_l_emplacement_et_le_nom_du_des_gabarits_csv_en_sortie = arcpy.GetParameterAsText(10)

# Local variables:
Valeur = "FILE"
bidon = Valeur
nom = "FILE"
v_nom__wgs_shp = "%Valeur%\\%nom%_wgs.shp"

# Process: Analyser un chemin
arcpy.ParsePath_mb(Couche_en_entrée, "PATH")

# Process: Erreur_Chemin
arcpy.gp.toolbox = "Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx";
# Warning: the toolbox Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.ErreurChemin(...) with arcpy.ErreurChemin_ALIAS(...)
arcpy.gp.ErreurChemin(Valeur)

# Process: Analyser un chemin (2)
arcpy.ParsePath_mb(Couche_en_entrée, "NAME")

# Process: Projeter
arcpy.Project_management(Couche_en_entrée, v_nom__wgs_shp, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "", "", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: gabarit_Phis_Sep_facul
arcpy.gp.toolbox = "Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx";
# Warning: the toolbox Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.gabaritPhisSep2(...) with arcpy.gabaritPhisSep2_ALIAS(...)
arcpy.gp.gabaritPhisSep2(v_nom__wgs_shp, Sélectionner_le_champ_comportant_l_alias, Sélectionner_le_champ_comportant_le_n°_de_l_essai, Sélectionner_le_champ_comportant_le_n°_du_bloc, Sélectionner_le_champ_comportant_l_uri_de_l_uc, Sélectionner_le_champ_comportant_l_uri_de_la_variété, Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°1, Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°2, Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°3, Sélectionner_un_champ_contenant_des_informations_supplémentaires_à_ajouter_au_gabarit__uri_d’une_autre_variété_ou_uri_d’une_modalité_de_facteur__n°4, Donner_l_emplacement_et_le_nom_du_des_gabarits_csv_en_sortie)

