# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# gen_gabarit_phis_uc.py
# Created on: 2022-08-19 08:26:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: gen_gabarit_phis_uc <Couche_en_entrée> <Cocher_le_champ_comportant_le_s__nom_s__de_s__UC> <Donner_l_emplacement_et_le_nom_du_gabarit_csv_en_sortie> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Modéliser les fonctions")
arcpy.ImportToolbox("Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx")

# Script arguments
Couche_en_entrée = arcpy.GetParameterAsText(0)

Cocher_le_champ_comportant_le_s__nom_s__de_s__UC = arcpy.GetParameterAsText(1)

Donner_l_emplacement_et_le_nom_du_gabarit_csv_en_sortie = arcpy.GetParameterAsText(2)

# Local variables:
Valeur = "FILE"
bidon = Valeur
nom = "FILE"
v_nom__wgs_shp = "%Valeur%\\%nom%_wgs.shp"
fus = "in_memory\\fus"
select_uc = "%Cocher le champ comportant le(s) nom(s) de(s) UC%"

# Process: Analyser un chemin
arcpy.ParsePath_mb(Couche_en_entrée, "PATH")

# Process: Erreur_Chemin
arcpy.gp.toolbox = "Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx";
# Warning: the toolbox Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.ErreurChemin(...) with arcpy.ErreurChemin_ALIAS(...)
arcpy.gp.ErreurChemin(Valeur)

# Process: Analyser un chemin (2)
arcpy.ParsePath_mb(Couche_en_entrée, "NAME")

# Process: Projeter
arcpy.Project_management(Couche_en_entrée, v_nom__wgs_shp, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "", "", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Fusionner
arcpy.Dissolve_management(v_nom__wgs_shp, fus, Cocher_le_champ_comportant_le_s__nom_s__de_s__UC, "", "MULTI_PART", "DISSOLVE_LINES")

# Process: gabarit_phis_UC
arcpy.gp.toolbox = "Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx";
# Warning: the toolbox Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.GabPhisUC(...) with arcpy.GabPhisUC_ALIAS(...)
arcpy.gp.GabPhisUC(fus, select_uc, Donner_l_emplacement_et_le_nom_du_gabarit_csv_en_sortie)

