# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# grille_poly.py
# Created on: 2022-08-19 08:26:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: grille_poly <Vecteur_directeur> <Nombre_de_cellules_selon_l_axe_donné_par_le_vecteur_directeur__nombre_de_planches_> <Nombre_de_cellules_selon_l_autre_axe__nombre_de_lignes_> <Taille_des_côtés_des_cellules_selon_l_autre_axe__largeur_des_lignes_> <Taille_des_côtés_des_cellules_selon_l_axe_donné_par_le_vecteur_directeur__largeur_des_planches_> <Couche_de_polygones_en_sortie> <Couche_de_la_grille_en_sortie> 
# Description: 
# Glisser-déposer de la couche du vecteur possible.
# ___________________________________________________
# On obtient en sortie :
# la couche des micro-parcelles (polygones) de la plateforme (en Lambert 93 et avec les champs ‘planche’ et ‘ligne’ vide)
# et la couche du quadrillage (polylignes) (en WGS 84)
# ___________________________________________________
# notes :
# La couche correspondant au quadrillage ne s’affiche pas directement sur la carte à la fin de l’exécution du modèle.
# Ce modèle poly_grille n’est pas utilisable pour certaines plateformes avec une grille irrégulière 

# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx")

# Script arguments
Vecteur_directeur = arcpy.GetParameterAsText(0)

Nombre_de_cellules_selon_l_axe_donné_par_le_vecteur_directeur__nombre_de_planches_ = arcpy.GetParameterAsText(1)

Nombre_de_cellules_selon_l_autre_axe__nombre_de_lignes_ = arcpy.GetParameterAsText(2)

Taille_des_côtés_des_cellules_selon_l_autre_axe__largeur_des_lignes_ = arcpy.GetParameterAsText(3)

Taille_des_côtés_des_cellules_selon_l_axe_donné_par_le_vecteur_directeur__largeur_des_planches_ = arcpy.GetParameterAsText(4)

Couche_de_polygones_en_sortie = arcpy.GetParameterAsText(5)

Couche_de_la_grille_en_sortie = arcpy.GetParameterAsText(6)

# Local variables:
interm = ""
quadrillage_L93 = interm
avec_planche_vide = Couche_de_polygones_en_sortie
avec_ligne_vide = avec_planche_vide

# Process: Quadri
arcpy.gp.toolbox = "Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx";
# Warning: the toolbox Q:/UE/7-SIG/bases_données_SIG/model_builder/MB_UE.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Quadri(...) with arcpy.Quadri_ALIAS(...)
arcpy.gp.Quadri(Vecteur_directeur, interm, Taille_des_côtés_des_cellules_selon_l_autre_axe__largeur_des_lignes_, Taille_des_côtés_des_cellules_selon_l_axe_donné_par_le_vecteur_directeur__largeur_des_planches_, Nombre_de_cellules_selon_l_axe_donné_par_le_vecteur_directeur__nombre_de_planches_, Nombre_de_cellules_selon_l_autre_axe__nombre_de_lignes_)

# Process: Définir une projection
arcpy.DefineProjection_management(interm, "PROJCS['RGF_1993_Lambert_93',GEOGCS['GCS_RGF_1993',DATUM['D_RGF_1993',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',700000.0],PARAMETER['False_Northing',6600000.0],PARAMETER['Central_Meridian',3.0],PARAMETER['Standard_Parallel_1',44.0],PARAMETER['Standard_Parallel_2',49.0],PARAMETER['Latitude_Of_Origin',46.5],UNIT['Meter',1.0]]")

# Process: Projeter
arcpy.Project_management(quadrillage_L93, Couche_de_la_grille_en_sortie, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "", "", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Entités vers polygones
arcpy.FeatureToPolygon_management("''", Couche_de_polygones_en_sortie, "", "ATTRIBUTES", "")

# Process: Ajouter champ planche
arcpy.AddField_management(Couche_de_polygones_en_sortie, "planche", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Ajouter champ ligne
arcpy.AddField_management(avec_planche_vide, "ligne", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

